version: '3.8'
services:
  db:
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       - ./data:/var/lib/postgresql/data
       - ./PostgreSQL/docker-entrypoint-initdb.d/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - postgres
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: stock_market_predictor_backend:dev
    environment:
      - FLASK_ENV=development
    ports:
      - '5000:5000'
    networks:
      - postgres
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
